server: &server
  adapter: postgresql
  encoding: unicode
  reconnect: false
  pool: 5
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: postgres

development:
  adapter: postgresql
  database: db/development_mail_assemble
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: db/test_mail_assemble
  pool: 5
  timeout: 5000

production:
  <<: *server
  adapter: postgresql
  database: db/mail_assemble
  pool: 5
  timeout: 5000
