server: &server
  adapter: postgresql
  encoding: unicode
  reconnect: false
  pool: 5
  host: 127.0.0.1
  port: 5432

development:
  adapter: postgresql
  database: db/autoresponder_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: db/autoresponder_test
  pool: 5
  timeout: 5000

production:
  <<: *server
  adapter: postgresql
  database: db/autoresponder_production
  pool: 5
  timeout: 5000
